### ISSUE TITLE
多数据源分页查询bug

### ISSUE THREAD

**Issue by akacd** [zhangdaiscott/jeecg#22]
分页查询条件组装时没有组装页面传入的参数。
问题描述：http://www.jeecg.org/forum.php?mod=viewthread&tid=5648&page=1#pid15174
在CgReportController.java 中增加getFullSql，组装参数，即可解决该问题：
if(StringUtils.isNotBlank(dbKey)){
               querySql=SqlUtil.getFullSql(querySql,queryparams);//duchao 20180423 add to support query
            result= DynamicDBUtil.findList(dbKey,SqlUtil.jeecgCreatePageSql(dbKey,querySql,queryparams,p,r));
            Map map=(Map)DynamicDBUtil.findOne(dbKey,SqlUtil.getCountSql(querySql,null));
            if(map.get("COUNT(*)") instanceof BigDecimal){
                    BigDecimal count = (BigDecimal)map.get("COUNT(*)");
                    size = count.longValue();
            }else{
                    size=(Long)map.get("COUNT(*)");
            }
        }else{
            result= cgReportService.queryByCgReportSql(querySql, queryparams, p, r);
            size = cgReportService.countQueryByCgReportSql(querySql, queryparams);
        }

**Comment by zhangdaiscott** [comment]
感谢，新版已经修复
