### ISSUE TITLE
不支持oracle 的语句

### ISSUE THREAD

**Issue by sean--wang** [zhangdaiscott/jeecg#23]
ORACLE 数据库添加组织架构报错 
[2018-04-28 16:19:21] [ERROR] [org.jeecgframework.core.common.exception.GlobalExceptionResolver:86] 全局处理异常捕获:
java.sql.SQLException: ORA-00904: "LEFT": 标识符无效

**Comment by sean--wang** [comment]
在org.jeecgframework.web.system.controller.core.SystemController  747行

	sb.append(" and LEFT(org_code,1)='A'");

**Comment by zhangdaiscott** [comment]
private synchronized String getMaxLocalCode(String parentCode){
		if(oConvertUtils.isEmpty(parentCode)){
			parentCode = "";
		}
		int localCodeLength = parentCode.length() + YouBianCodeUtil.zhanweiLength;
		StringBuilder sb = new StringBuilder();
		sb.append("SELECT org_code FROM t_s_depart");
		//-update-begin--author:scott--date:20160414--for:数据库兼容性修改---
		if(ResourceUtil.getJdbcUrl().indexOf(JdbcDao.DATABSE_TYPE_SQLSERVER)!=-1){
			sb.append(" where LEN(org_code) = ").append(localCodeLength);
		}else{
			sb.append(" where LENGTH(org_code) = ").append(localCodeLength);
		}
		//-update-end--author:scott--date:20160414--for:数据库兼容性修改---
		if(oConvertUtils.isNotEmpty(parentCode)){
			sb.append(" and  org_code like '").append(parentCode).append("%'");
		} else {
			//-update-begin--author:LiShaoQing --date:20180104--for:只取非供应商节点---
			sb.append(" and LEFT(org_code,1)='A'");
			//-update-end--author:LiShaoQing --date:20180104--for:只取非供应商节点---
		}
		//update-begin-Alex 20160310 for:去除LIMIT,解决数据库兼容性问题
		sb.append(" ORDER BY org_code DESC");
		List<Map<String, Object>> objMapList = systemService.findForJdbc(sb.toString(), 1, 1);
		String returnCode = null;
		if(objMapList!=null && objMapList.size()>0){
			returnCode = (String)objMapList.get(0).get("org_code");
		}
		//update-end-Alex 20160310 for:去除LIMIT,解决数据库兼容性问题
		return returnCode;
	}

**Comment by zhangdaiscott** [comment]
minidao的数据库类型没改吧
